#################################################
## Management endpoints configurations
#################################################
management.endpoints.web.exposure.include=info,health,env
management.endpoint.health.show-details=always

#################################################
## Database connection configuration
#################################################

spring.data.mongodb.uri=mongodb://localhost:27017/windows_local