package com.probe.stack.code.generator.component;

import com.probe.stack.code.generator.parser.ControllerMetadataExtractor.ControllerMetadata;
import com.squareup.javapoet.*;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.mongodb.repository.MongoRepository;
import org.springframework.stereotype.Component;

import javax.lang.model.element.Modifier;
import java.io.File;
import java.io.IOException;

/**
 * Generates MongoDB repository interfaces from controller metadata.
 *
 * @author ProbeStack
 */
@Slf4j
@Component
public class RepositoryInterfaceGenerator {

    /**
     * Generates a MongoDB repository interface for the given entity.
     *
     * @param metadata controller metadata
     * @param outputDir output directory for generated files
     * @throws IOException if file writing fails
     */
    public void generateRepositoryInterface(ControllerMetadata metadata, File outputDir) throws IOException {
        String entityClass = metadata.getEntityClass();

        // Validate entity class
        if (entityClass == null || entityClass.isEmpty() || entityClass.equals("null")) {
            throw new IllegalArgumentException(
                    "Cannot generate repository: Entity class not found for controller: " + metadata.getClassName()
            );
        }

        // Validate and normalize package name
        String basePackage = normalizePackageName(metadata.getPackageName());
        String repositoryPackage = calculateRepositoryPackage(basePackage);
        String modelPackage = calculateModelPackage(basePackage);
        String repositoryName = generateRepositoryName(entityClass);

        log.info("Generating repository:");
        log.info("  Repository: {}", repositoryName);
        log.info("  Base Package: {}", basePackage);
        log.info("  Repository Package: {}", repositoryPackage);
        log.info("  Model Package: {}", modelPackage);

        // Create parameterized MongoRepository<Entity, String>
        ClassName entityClassName = ClassName.get(modelPackage, entityClass);
        ClassName stringClass = ClassName.get(String.class);
        TypeName mongoRepositoryType = ParameterizedTypeName.get(
                ClassName.get(MongoRepository.class),
                entityClassName,
                stringClass
        );

        // Build repository interface
        TypeSpec repositoryInterface = TypeSpec.interfaceBuilder(repositoryName)
                .addModifiers(Modifier.PUBLIC)
                .addSuperinterface(mongoRepositoryType)
                .addJavadoc("MongoDB repository for $L entities.\n", entityClass)
                .addJavadoc("\n<p>This repository extends MongoRepository which provides standard CRUD operations:</p>\n")
                .addJavadoc("<ul>\n")
                .addJavadoc("<li>save(entity) - Create or update an entity</li>\n")
                .addJavadoc("<li>findById(id) - Find entity by ID</li>\n")
                .addJavadoc("<li>findAll() - Retrieve all entities</li>\n")
                .addJavadoc("<li>existsById(id) - Check if entity exists</li>\n")
                .addJavadoc("<li>deleteById(id) - Delete entity by ID</li>\n")
                .addJavadoc("<li>count() - Count all entities</li>\n")
                .addJavadoc("</ul>\n")
                .addJavadoc("\n@author Generated by ProbeStack CodeGen")
                .build();

        // Write to file
        JavaFile javaFile = JavaFile.builder(repositoryPackage, repositoryInterface)
                .indent("    ")
                .build();

        javaFile.writeTo(outputDir);

        log.info("Successfully generated repository: {}", repositoryName);
    }

    /**
     * Generates repository interface name from entity class name.
     * Simply appends "Repository" to entity name.
     */
    private String generateRepositoryName(String entityClass) {
        if (entityClass == null || entityClass.isEmpty()) {
            throw new IllegalArgumentException("Entity class name cannot be null or empty");
        }
        return entityClass + "Repository";
    }

    /**
     * Normalizes package name by removing any incorrect prefixes.
     */
    private String normalizePackageName(String packageName) {
        if (packageName == null || packageName.isEmpty()) {
            throw new IllegalArgumentException("Package name cannot be null or empty");
        }

        // Remove common incorrect prefixes
        packageName = packageName.replaceFirst("^(service|repository|model|controller|api)\\.", "");

        log.debug("Normalized package: {}", packageName);
        return packageName;
    }

    /**
     * Calculates repository package from base package.
     */
    private String calculateRepositoryPackage(String basePackage) {
        // Remove .api suffix if present
        String cleanPackage = basePackage.replaceAll("\\.api$", "");
        return cleanPackage + ".repository";
    }

    /**
     * Calculates model package from base package.
     */
    private String calculateModelPackage(String basePackage) {
        String cleanPackage = basePackage.replaceAll("\\.api$", "");
        return cleanPackage + ".model";
    }
}